version: "3.8"

services:
  web:
    build:
      context: .
    container_name: fastapi_backend
    command: /app/docker-entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - fastapi_network

  db:
    image: postgres:16
    container_name: fastapi_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - fastapi_network

volumes:
  postgres_data:

networks:
  fastapi_network: